# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90bd10b609ed8be27e4b39737e2efb77561831dab7394e938f7f6698a3d17fac6ff65327cb4ffdd9addb7b6f621d9e22e3b15d98f872fe85be28ef5736d3a260

test:
  secret_key_base: c6847a0d42adea687b688b3d9da54cd01b5fc5243d4d1c7546f1e8136a22bc0d286387d38bc2082dba52f793b660e5bb78849bbf7157a0094f78a70502138ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
